{% set version = "4.10.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 699103c8e64886e3ec7053f2a6aa83bb90426063526f63a818732ff385202bad

build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    - python -m ipykernel install --prefix {{ PREFIX }}

requirements:
  build:
    - pip
    - python
    - jupyter_client
    - ipython >=4.0
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0
    - traitlets >=4.1
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: https://ipython.org
  license: BSD 3-clause
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
    - blink1073
    - Carreau
