{% set name = "ipykernel" %}
{% set version = "6.19.2" %}

{% set migrating = false %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ab68d3d3654196266baa93990055413e167263ffbe4cfe834f871bcd3d3506d

build:
  number: 0
  skip: true  # [py<37]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - {{ PYTHON }} -m ipykernel install --sys-prefix
    # TODO: this may be needed/desirable at some point
    # - cd {{ RECIPE_DIR }} && {{ PYTHON }} fix_kernelspec.py
  script_env:
    - MIGRATING={{ migrating }}

requirements:
  host:
    - python
    - debugpy >=1.0.0
    - hatchling >=1.4
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - packaging
    - pip
    - psutil
    - wheel
  run:
    - appnope  # [osx]
    - comm >=0.1
    - debugpy >=1.0
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - matplotlib-inline >=0.1
    - nest-asyncio
    - packaging
    - psutil
    - python
    - pyzmq >=17
    - tornado >=6.1
    - traitlets >=5.1.0

test:
  requires:
    - curio  # [not win]
    - flaky
    - jupyter_client
    - numpy
    - pip
    - pytest >=6.0
    - pytest-asyncio
    - pytest-cov
    - pytest-timeout
    - trio
    {% if not migrating %}
    - ipyparallel
    - matplotlib-base
    {% endif %}

  imports:
    - ipykernel
  commands:
    - pip check
    - jupyter kernelspec list

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  license_url: https://github.com/ipython/ipykernel/blob/main/COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - davidbrochart
