{% set version = "6.0.0" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: 65433238970dc6414a3ebca6f7a819fed0551efba9ac1da816ada778eb47ec65

build:
  number: 0
  skip: true  # [py<36]
  script:
    - {{ PYTHON }} setup.py bdist_wheel
    - cd dist
    - {{ PYTHON }} -m pip install ipykernel-{{ version }}-py3-none-any.whl --no-deps -vv
    - {{ PYTHON }} -m ipykernel install --sys-prefix
    # TODO: this may be needed/desirable at some point
    # - cd {{ RECIPE_DIR }} && {{ PYTHON }} fix_kernelspec.py

requirements:
  {% if not win %}
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ipython >=5.0                          # [build_platform != target_platform]
    - jupyter_client                         # [build_platform != target_platform]
  {% endif %}
  host:
    - debugpy >=1
    - ipython >=7.23.1
    - jupyter_client
    - pip
    - python
  run:
    - appnope  # [osx]
    - debugpy >=1
    - importlib-metadata <4  # [py<38]
    - ipython >=7.23.1
    - jupyter_client
    - matplotlib-inline >=0.1.0,<0.2.0
    - python
    - tornado >=4.2
    - traitlets >=4.1.0

test:
  requires:
    - curio  # [not win]
    - flaky
    - ipyparallel
    - matplotlib-base
    - nose
    - numpy
    - pip
    - pytest !=5.3.4
    - pytest-cov
    - pytest-timeout
    - trio

  imports:
    - ipykernel
  commands:
    - pip check
    - jupyter kernelspec list

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipython.readthedocs.io
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
