{% set version = "4.8.2" %}

package:
  name: ipykernel
  version: {{ version }}

source:
  fn: ipykernel-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-{{ version }}.tar.gz
  sha256: c091449dd0fad7710ddd9c4a06e8b9e15277da306590bc07a3a1afa6b4453c8f

build:
  number: 0
  script:
    - pip install --no-deps .
    - python -m ipykernel install --prefix $PREFIX  # [not win]
    - python -m ipykernel install --prefix %PREFIX%  # [win]

requirements:
  host:
    - pip
    - python
    - jupyter_client
    - ipython
    - tornado >=4.0
  run:
    - python
    - ipython >=4.0.0
    - traitlets >=4.1
    - jupyter_client
    - tornado >=4.0

test:
  imports:
    - ipykernel

about:
  home: http://ipython.org
  license: BSD 3-clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  doc_url: http://ipykernel.readthedocs.io/en/latest/
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - ocefpaf
