{% set name = "ipykernel" %}
{% set version = "6.31.0" %}

{% set migrating = false %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2372ce8bc1ff4f34e58cafed3a0feb2194b91fc7cad0fc72e79e47b45ee9e8f6

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
    - {{ PYTHON }} -m ipykernel install --sys-prefix
    # TODO: this may be needed/desirable at some point
    # - cd {{ RECIPE_DIR }} && {{ PYTHON }} fix_kernelspec.py
  script_env:
    - MIGRATING={{ migrating }}

requirements:
  host:
    - python
    - pip
    - hatchling >=1.22
    - jupyter_client >=6
    - ipython >=7.23.1
    - comm >=0.1.1
    - psutil >=5.7
  run:
    - python
    - appnope >=0.1.2  # [osx]
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=8.0.0
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio >=1.4
    - packaging >=22
    - psutil >=5.7
    - pyzmq >=25
    - tornado >=6.2
    - traitlets >=5.4.0

test:
  source_files:
    - pyproject.toml
    - tests
  requires:
    - pip
    # cyclic dependency between ipykernel and ipyparallel / jupyter_client
    #- ipyparallel
    - curio  # [not win]
    - flaky
    - matplotlib-base
    - numpy
    - pytest >=7.0,<9
    - pytest-asyncio >=0.23.5
    # The 6 failing tests in test_subshells.py::test_run_concurrently_sequence all fail 
    # because the test code attempts to check for pytest's --cov option (from pytest-cov plugin) 
    # but doesn't handle the case where the option doesn't exist, causing ValueError: no option named '--cov'.
    - pytest-cov
    - pytest-timeout
  commands:
    - pip check
    - jupyter kernelspec list
    - python run_test.py

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
  description: |
    A powerful interactive Python shell and a Jupyter kernel to work with
    Python code in Jupyter notebooks and other interactive frontends.
  dev_url: https://github.com/ipython/ipykernel
  doc_url: https://ipykernel.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
    - Carreau
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - davidbrochart
