travis:
  secure:
    BINSTAR_TOKEN: mVXQlqOs1uQwvgnVWfYS4W5ae0CiiNMvbDF+n785fvpViIOX/Fi180I7fanwoH0sTCY65gxpRiH5N5HXiGVcwU1FkjZ0RxYNzONbG1SBIIkmNsA3PZtG/+tp5NltumK1tC7diOcOuCHfSkmYjIXG0RRIqUjbzOF/CCIQH6X6yIWvynMWpWtZ2EtFn9IgTrCil4dXMO/PJnkSYRqJkcE/98lqApTm5MIiQTml3WqDJgK4e9JuaGRU0EGjqf3Fuw1OC+unw4/skBmo2y6ShEx8cwgR9unCUzWmZao77gWYIYVahNWw7JhuJgNCPThLCmPT0QY87Nt4GbuvMNPKvbdpfzS1UzTJ4jZdml4XGzIoElvrElgdR1o3DP64PPG1nRcXHonPHsMIZdf6b5udm7OXjbxwC5UsUzVQ36ECY+nlZsMoudhl65XCVtt+RTqxc9zMNfabbiTagld9mvTUTK18lLmrAfehHnToCLSx26uC4QmFBQEX7kZQn1kiCYqVxeoyaTRd/7g5Jue4i19+Hj6Cw6hY55vhLlTwsqnBW0hQPHfz2bITcvIWSwn8VxSTFRqLefPJxmW2VIWhMOk3s05CBGd845hSwKmUP46/O1GKwGvqL5KD3Psxa8co4LmR8RUeUXFYJeRVkKAgCk/BVv2w95s3tUzLwLa4XeQknls03PI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
