travis:
  secure:
    BINSTAR_TOKEN: Lxv/Fftc7L4fbKEY1bscbjqom7gwLWh6+HypzjLC/ItMRh/zEwWsLvIGbUcCdm1pxrHAJNV13mmRWbbtf2zn8viAWzxOlkRSjKvmJOGk74uFe+bV/8osGE28i//ExnIpAD1ZSxtMfisyAFHd52376yvVnGMD8nzd0B2h8J3+q8rjDNcqn5wHqQrAdLiZsu9p44xhaYFqjbM3Dj7vMoKDAlRmO3zMTgxpLMgFuw3AR0a+sesRomExRaryKTFuZbv6+YpyYPcmQ95SYI2JrvdDvoJ35pGGYJDoPG9h6D1tt8o3IH242Edr1ZlvwL+Jy+G7yODNlYjTklFXQgPayU93nNw8yF7+hHQRF8QyrI5xY0Es6CpwjkinKpmohH825xIDNYPJZMOokqFjQFVBdUkz9vCXtgazo/TUGF1iGROTcQ2EYKSGiT23JxMobfcws1P731iU9M1mocJJEWzK0dVvgbN0K8I4PQ4h4fo2bk7MKDsma1c0/FbeNajd/xcj23lUEHLYHGu7uvBK7AhIfe/bjbCI3bv5jYQHObmtfJutkyoRI/VSH92dV0JBBPnQ35MefimAUtyHAnY0jXa7tlsmAmueGob2a9uhD63BFrmwybCFCG+4oZQPrKYh2wSXkc9TvrC/AXqsnE30gLM9hHJONVSi6roQo6Cp3QYrr1Xz8Ww=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
